module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 150],
    'scope-case': [0, 'always'],
    'type-enum': [
      1,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'review',
        'release',
        'upgrade',
        'downgrade',
        'deployment',
        'hotfix',
        'security',
      ],
    ],
  },
  parserPreset: 'conventional-changelog-angular-emoji',
};
